### ISSUE TITLE
Generate image from my captions

### ISSUE THREAD

**Issue by alfennec** [tobran/DF-GAN#10]
After training the network, how to generate image from my own captions?

**Comment by mertbozkir** [comment]
did you find anything useful ?

**Comment by cientgu** [comment]
Same issue. Does anyone find to solve it?

**Comment by tobran** [comment]
> i don't know way you close this issue, we did not receive an answer, I train my own model , but I can't generrate image from my own captions
We update the code, and it supports the generation from your captions.
