### ISSUE TITLE
RNN_ENCODER size mismatch

### ISSUE THREAD

**Issue by rishi-wqd190004** [tobran/DF-GAN#12]
Hi, I have cloned the repository and have been following the steps mentioned in the readme.md file.
While following the steps: The text encoder (pretrained for CUB dataset) is giving the below error:

`File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RNN_ENCODER:
	size mismatch for encoder.weight: copying a param with shape torch.Size([5450, 300]) from checkpoint, the shape in current model is torch.Size([1, 300]).`

Anyone can share some thoughts and a solution for the same.

I do understand that there is a mismatch on shape but i am unable to pinpoint the exact position this is happening.

Package versions with python3.7:
`torch                         1.9.0+cu102
torchsummary                  1.5.1
torchtext                     0.10.0
torchvision                   0.10.0+cu102`

**Comment by avideep** [comment]
I think the authors of this repo have not provided the code for training the RNN and CNN Encoders in `DAMSM.py`. The encoders need to be trained again (or at best fine tuned) on the new dataset that has a new vocabulary size.

**Comment by rishi-wqd190004** [comment]
@avideep yeah i do agree with you, hence was wondering did you train an encoder for char-CNN-RNN for your own dataset? If so do you mind sharing about that.

**Comment by avideep** [comment]
No, I haven't written any training routines for the DAMSM encoders yet. If I do, I'll share it with you. Meanwhile, you can use the coco-pretrained DAMSM encoders also, just replace the argument `dataset.n_words` with the vocab length of coco while initializing the `RNNEncoder()`.

**Comment by rishi-wqd190004** [comment]
Thanks @avideep for the information, I have been trying to plug in data [from this challenge in 2018](https://eval.ai/web/challenges/challenge-page/86/overview). I was trying to train a text encoder for the same. Wanted to generate images based on text for the above dataset. If possible to share how can this be implemented will be really helpful.
Could you please let me know where in the code files can i do : 'Meanwhile, you can use the birds-pretrained DAMSM encoders also, just replace the argument dataset.n_words with the vocab length of birds while initializing the RNNEncoder().'?

**Comment by avideep** [comment]
You can find the training routines of DAMSM encoders in [this file](https://github.com/taoxugit/AttnGAN/blob/master/code/pretrain_DAMSM.py).
