### ISSUE TITLE
Fid Score on the CUB dataset

### ISSUE THREAD

**Issue by fuyou123** [tobran/DF-GAN#14]
On CUB dataset, we used the pre-training model provided by the official website for testing, then the calculated result was 26.89 in the Fid score. However, the result shown on the paper was 14.81.  May I ask what causes such a big difference?

**Comment by tobran** [comment]
The FID 14.81 is the result of new DF-GAN, we updated some modules, you can compare the paper V1 and V2 on arxiv. We will update the code after CVPR2022 dealine. Thanks for your attention on our work.

**Comment by fuyou123** [comment]
在运行IS代码的时候，需要下载inception_finetuned_models.zip，但是由于没有权限导致下载失败。你能否，发一份给我，谢谢。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月11日(星期四) 下午5:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tobran/DF-GAN] Fid Score on the CUB dataset (Issue #14)





 
The FID 14.81 is the result of new DF-GAN, we updated some modules, you can compare the paper V1 and V2 on arxiv. We will update the code after CVPR2022 dealine. Thanks for your attention on our work.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fuyou123** [comment]
能方便加个qq进行进一步讨论一下好吗，qq:1529261573





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tobran/DF-GAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tobran/DF-GAN] Fid Score on the CUB dataset (Issue #14)





 
The FID 14.81 is the result of new DF-GAN, we updated some modules, you can compare the paper V1 and V2 on arxiv. We will update the code after CVPR2022 dealine. Thanks for your attention on our work.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by callmexiaowei** [comment]
> The FID 14.81 is the result of new DF-GAN, we updated some modules, you can compare the paper V1 and V2 on arxiv. We will update the code after CVPR2022 dealine. Thanks for your attention on our work.

您好，您发的这个代码是没有更新的代码吧，我下载了您训练的模型，FID只有21，大概什么时候会更新FID和IS值最好的代码呢？

**Comment by fuyou123** [comment]
那你能发一份计算IS指标的代码给我吗，拜托



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月28日(星期四) 晚上7:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tobran/DF-GAN] Fid Score on the CUB dataset (Issue #14)





  
The FID 14.81 is the result of new DF-GAN, we updated some modules, you can compare the paper V1 and V2 on arxiv. We will update the code after CVPR2022 dealine. Thanks for your attention on our work.
  
您好，您发的这个代码是没有更新的代码吧，我下载了您训练的模型，FID只有21，大概什么时候会更新FID和IS值最好的代码呢？

**Comment by callmexiaowei** [comment]
> 那你能发一份计算IS指标的代码给我吗，拜托
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年4月28日(星期四) 晚上7:37 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [tobran/DF-GAN] Fid Score on the CUB dataset (Issue #14) The FID 14.81 is the result of new DF-GAN, we updated some modules, you can compare the paper V1 and V2 on arxiv. We will update the code after CVPR2022 dealine. Thanks for your attention on our work. 您好，您发的这个代码是没有更新的代码吧，我下载了您训练的模型，FID只有21，大概什么时候会更新FID和IS值最好的代码呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

qq 1975993291
