### ISSUE TITLE
代码里面没有lib.datasets

### ISSUE THREAD

**Issue by Heavenhjs** [tobran/DF-GAN#19]
感谢作者上传新版本的代码，我正尝试复现，但发现有如下问题
在train.py的21行有如下代码：
from lib.datasets import get_fix_data`

包括modules中也用到了datasets：
from lib.datasets import TextImgDataset as Dataset
from lib.datasets import prepare_data, encode_tokens

lib文件夹中暂未找到datasets文件，是否上传遗漏，还是我复现步骤错误

**Comment by tobran** [comment]
感谢提醒，由于gitignore里面填了/data*，导致dataset.py未被同步，目前已更新。同时我们会在今天上传预处理的数据集，训练好的模型，并且更新readme，可以根据新的readme进行复现。

**Comment by Heavenhjs** [comment]
> 感谢提醒，由于gitignore里面填了/data*，导致dataset.py未被同步，目前已更新。同时我们会在今天上传预处理的数据集，训练好的模型，并且更新readme，可以根据新的readme进行复现。

非常感谢
