### ISSUE TITLE
where to download the textencoder pretrained file?

### ISSUE THREAD

**Issue by houyun668** [tobran/DF-GAN#20]
RuntimeError: Error(s) in loading state_dict for RNN_ENCODER:
	size mismatch for encoder.weight: copying a param with shape torch.Size([5450, 300]) from checkpoint, the shape in current model is torch.Size([5598, 300]).

**Comment by tobran** [comment]
The pre-trained text encoder files are saved in our preprocessed metadata. 
You can download our preprocessed metadata, we have provided the link in readme.
