### ISSUE TITLE
About the differences between V1, V2 and V3 version paper code

### ISSUE THREAD

**Issue by bobo12391** [tobran/DF-GAN#21]
I checked the code of the network structure of your V1 version and the current version, and found only two differences. When DFBlock fuses text information, the V1 version code only has sentence vectors, but the current version also combines noise. Then the gradient update of MAGP is changed from the original step-by-step update to the joint hinge loss joint update. Besides these two differences, are there any other differences?

我查阅了你的v1版本和当前版本的网络结构部分的代码，只发现了两处不同。当DFBlock融合文本信息的时候，v1版本代码只有句子向量，但当前版本还联合了噪音。然后MAGP进行梯度更新的时候从原来的分步更新变成了联合hinge loss一同更新。除了这两处不同外还有其他不同吗？

**Comment by tobran** [comment]
模型的主要变化如下：1. 去掉生成器Block中可学习的残差参数gamma（造成v1版本训练不稳定，甚至偶尔奔溃的重要原因）2. 噪声与句子向量concat（在coco上提升明显，可能是coco图片更加多样）3. 联合更新hinge loss和MAGP（有利于稳定收敛，实际上放大训练的max_epoch，会发现模型还能收敛，但比较缓慢）4. 增加了noise truncation（会有一点点提升，但只对当前版本有效，和改进2搭配使用，直接用在v1上反而会降低性能）。主要就这些，建议使用新版本代码进行训练，更加易用全面。

**Comment by bobo12391** [comment]
> 模型的主要变化如下：1. 去掉生成器Block中可学习的残差参数gamma（造成v1版本训练不稳定，甚至偶尔奔溃的重要原因）2. 噪声与句子向量concat（在coco上提升明显，可能是coco图片更加多样）3. 联合更新hinge loss和MAGP（有利于稳定收敛，实际上放大训练的max_epoch，会发现模型还能收敛，但比较缓慢）4. 增加了noise truncation（会有一点点提升，但只对当前版本有效，和改进2搭配使用，直接用在v1上反而会降低性能）。主要就这些，建议使用新版本代码进行训练，更加易用全面。

**Comment by bobo12391** [comment]
> 模型的主要变化如下：1. 去掉生成器Block中可学习的残差参数gamma（造成v1版本训练不稳定，甚至偶尔奔溃的重要原因）2. 噪声与句子向量concat（在coco上提升明显，可能是coco图片更加多样）3. 联合更新hinge loss和MAGP（有利于稳定收敛，实际上放大训练的max_epoch，会发现模型还能收敛，但比较缓慢）4. 增加了noise truncation（会有一点点提升，但只对当前版本有效，和改进2搭配使用，直接用在v1上反而会降低性能）。主要就这些，建议使用新版本代码进行训练，更加易用全面。


好的谢谢！

**Comment by junzhin** [comment]
你好我有两个相关的问题,
1. 您提到可学习的残差参数gamma, 在现版本中还需要的关注吗? 我假设你指的是https://github.com/tobran/DF-GAN/blob/64fc9c9eb1d99cfde0f8215fc4388588734b047c/code/models/GAN.py#L165C9-L165C34 中一行的gamma fc layers?
2.  对于在噪声与句子向量concat 的噪声的DFBlock 中, 省略相关的noise vector 的输出对于模型的学习有什么影响? (除了在coco 上提升明显之外), 其他的模型的performance的影响大吗?
