### ISSUE TITLE
how to generate images using only statements?

### ISSUE THREAD

**Issue by Hassan022020** [tobran/DF-GAN#4]
I have trained the model as per instructions but now I am stuck... how do I generate images using text only as there are no clear instructions for this in readme

**Comment by ZhaooweiZhong** [comment]
While, I met the same problem as U.

**Comment by srinivaspavan9** [comment]
> I have trained the model as per instructions but now I am stuck... how do I generate images using text only as there are no clear instructions for this in readme

Do you know what text encoder has been used for the datasets taken?

**Comment by skabbit** [comment]
Text Encoder is LSTM on trained model. But you can switch it on GRU during training.
It is in config.py line 20.

**Comment by cientgu** [comment]
So, how to test the model using my own caption?
